alias python=python3
alias pip=pip3
alias ls=eza
alias l="eza -lah"
alias cat=bat
alias zel=zellij
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gd="git diff HEAD"
alias gss="git status -s"
alias cr="cargo run"
alias ct="cargo test"
alias cb="cargo bench"
alias ca="cargo add"
