theme = "catppuccin_mocha"

# Copied a lot from https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
# movement
m = "move_char_left"
n = "move_line_down"
e = "move_line_up"
i = "move_char_right"
F = "move_next_long_word_end"
f = "move_next_word_end"
l = "search_next"
L = "search_prev"
"0" = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
S = "surround_add"
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
u = ["undo", "collapse_selection"]
U = ["redo", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
c = ["yank_main_selection_to_clipboard", "change_selection"]
y = "yank_main_selection_to_clipboard"
N = "join_selections"
ret = "jump_view_left"
"C-n" = "jump_view_down"
"C-e" = "jump_view_up"
tab = "jump_view_right"
"C-l" = "jump_forward"
"C-p" = "jump_backward"

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
n = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
e = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"] }

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.select]
# movement
m = "extend_char_left"
n = "extend_line_down"
e = "extend_line_up"
i = "extend_char_right"
F = "extend_next_long_word_end"
f = "extend_next_word_end"
L = "find_prev_char"
l = "find_next_char"
"0" = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
C = ["goto_line_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "change_selection"]
"%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
c = ["yank_main_selection_to_clipboard", "change_selection"]

# Visual-mode specific muscle memory
a = "select_textobject_around"

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

"/" = "toggle_comments"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space.w]
m = "jump_view_left"
n = "jump_view_down"
e = "jump_view_up"
i = "jump_view_right"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
true-color = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
right = ["position", "file-encoding", "file-type"]
