[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }
ruff = { command = "ruff-lsp", config = { settings = { run = "onSave" } } }

[[language]]
name = "python"
auto-format = true
roots = ["pyprojects.toml"]
language-servers = [ "pyright", "ruff" ]
