[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true
roots = ["pyprojects.toml"]
language-servers = [ "pyright" ]

[[language]]
name = "cpp"
auto-format = true
